## import library

In [10]:
import numpy as np

## Input Texts

In [11]:
text1='deal'
text2='leda'

## Initialize the algorithm

In [12]:
dist=np.zeros((len(text1)+1,len(text2)+1))
dist[0,:]=np.arange(len(text2)+1)
dist[:,0]=np.arange(len(text1)+1)
print(dist)

[[0. 1. 2. 3. 4.]
 [1. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0.]
 [3. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0.]]


## Dynamic programming to calculate minimum edit distance

In [13]:
for i in range(1,len(text1)+1):
    for j in range(1,len(text2)+1):
        if text1[i-1]==text2[j-1]:
            dist[i,j]=dist[i-1,j-1]
        else:
            dist[i,j]=min(  dist[i-1,j] +1 ,
                            dist[i,j-1] +1 ,
                            dist[i-1,j-1] + 2)
print(dist)

[[0. 1. 2. 3. 4.]
 [1. 2. 3. 2. 3.]
 [2. 3. 2. 3. 4.]
 [3. 4. 3. 4. 3.]
 [4. 3. 4. 5. 4.]]


## Results

In [14]:
print('Minimum Edit Distance Cost: ',dist[-1,-1])

Minimum Edit Distance Cost:  4.0


In [15]:
# transpose the dist
np.transpose(dist)

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 3.],
       [2., 3., 2., 3., 4.],
       [3., 2., 3., 4., 5.],
       [4., 3., 4., 3., 4.]])