## References 
- https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/

## Imports Libary 


In [8]:
import numpy as np
# import pandas as pd

## Univariate LSTM Models
- Vanilla LSTM
- Stacked LSTM
- Bidirectional LSTM
- CNN LSTM
- ConvLSTM

## Data Ppreparation
- inputs
[10, 20, 30, 40, 50, 60, 70, 80, 90]

- outputs
    X,	    	y
10, 20, 30		40
20, 30, 40		50
30, 40, 50		60


In [4]:
def split_sequence(sequence,number_of_steps):
    x,y=list(),list()
    for i in range(len(sequence)):
        end_index=i+number_of_steps
        # print(end_index)
        if end_index>len(sequence)-1:
            break
        sequence_x=sequence[i:end_index]
        sequence_y=sequence[end_index]
        x.append(sequence_x)
        y.append(sequence_y)
        # print(x)
        # print(y)

    return x,y




sequence=[10,20,30,40,50,60,70,80,90]
number_of_steps =3
x,y=split_sequence(sequence,number_of_steps)
print('Input features: ',x)
print('Labels: ',y)

Input features:  [[10, 20, 30], [20, 30, 40], [30, 40, 50], [40, 50, 60], [50, 60, 70], [60, 70, 80]]
Labels:  [40, 50, 60, 70, 80, 90]


In [5]:
for i in range(len(x)):
    print('input: ',x[i])
    print('output: ',y[i])

input:  [10, 20, 30]
output:  40
input:  [20, 30, 40]
output:  50
input:  [30, 40, 50]
output:  60
input:  [40, 50, 60]
output:  70
input:  [50, 60, 70]
output:  80
input:  [60, 70, 80]
output:  90


In [9]:
x_array=np.array(x)
y_array=np.array(y)
print(x_array.shape)
print(y_array.shape)


(6, 3)
(6,)


In [10]:
number_of_features=1
x_reshaped=x_array.reshape(x_array.shape[0],x_array.shape[1],number_of_features)
print(x_reshaped.shape)
x_reshaped

(6, 3, 1)


array([[[10],
        [20],
        [30]],

       [[20],
        [30],
        [40]],

       [[30],
        [40],
        [50]],

       [[40],
        [50],
        [60]],

       [[50],
        [60],
        [70]],

       [[60],
        [70],
        [80]]])

## Vanilla LSTM
A Vanilla LSTM is an LSTM model that has a single hidden layer of LSTM units, and an output layer used to make a prediction.

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM

In [12]:
model=Sequential()
model.add(LSTM(50,activation='relu',input_shape=(number_of_steps,number_of_features)))
model.add(Dense(1))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 50)                10400     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 51        
Total params: 10,451
Trainable params: 10,451
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.compile(optimizer='adam',loss='mse',metrics=['accuracy'])

In [14]:
history=model.fit(x_reshaped,y_array,epochs=200,verbose=1)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/200
6/6 [==============================] - 6s 1s/sample - loss: 4819.3623 - acc: 0.0000e+00
Epoch 2/200
6/6 [==============================] - 0s 831us/sample - loss: 4742.7817 - acc: 0.0000e+00
Epoch 3/200
6/6 [==============================] - 0s 831us/sample - loss: 4666.0835 - acc: 0.0000e+00
Epoch 4/200
6/6 [==============================] - 0s 665us/sample - loss: 4588.7070 - acc: 0.0000e+00
Epoch 5/200
6/6 [==============================] - 0s 499us/sample - loss: 4510.7778 - acc: 0.0000e+00
Epoch 6/200
6/6 [==============================] - 0s 831us/sample - loss: 4434.6631 - acc: 0.0000e+00
Epoch 7/200
6/6 [==============================] - 0s 499us/sample - loss: 4359.8296 - acc: 0.0000e+00
Epoch 8/200
6/6 [==============================] - 0s 499us/sample - loss: 4284.3115 - acc: 0.0000e+00
Epoch 9/200
6/6 [==============================] - 0s 665us/sample - loss: 4208.8379 

## Evaluate the model

In [15]:
x_input=[70,80,90]
x_input=np.array(x_input)
x_input=x_input.reshape(1,number_of_steps,number_of_features)
yhat=model.predict(x_input,verbose=1)
print(yhat)

1/1 [==============================] - 0s 286ms/sample
[[103.32941]]


In [18]:
print('Input: \n',x_input)
print('Predicted: ',yhat)

Input: 
 [[[70]
  [80]
  [90]]]
Predicted:  [[103.32941]]


## Stacked LSTM
Multiple hidden LSTM layers can be stacked one on top of another in what is referred to as a Stacked LSTM model.

An LSTM layer requires a three-dimensional input and LSTMs by default will produce a two-dimensional output as an interpretation from the end of the sequence.

We can address this by having the LSTM output a value for each time step in the input data by setting the 
return_sequences=True argument on the layer. This allows us to have 3D output from hidden LSTM layer as input to the next.

In [25]:
stacked_LSTM_model=Sequential()
stacked_LSTM_model.add(LSTM(50,activation='relu',return_sequences=True,input_shape=(number_of_steps,number_of_features)))
stacked_LSTM_model.add(LSTM(50,activation='relu'))
stacked_LSTM_model.add(Dense(1))

stacked_LSTM_model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_10 (LSTM)               (None, 3, 50)             10400     
_________________________________________________________________
lstm_11 (LSTM)               (None, 50)                20200     
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 51        
Total params: 30,651
Trainable params: 30,651
Non-trainable params: 0
_________________________________________________________________


In [26]:
stacked_LSTM_model.compile(optimizer='adam',loss='mse',metrics=['accuracy'])

In [27]:
history=stacked_LSTM_model.fit(x_reshaped,y_array,epochs=200,verbose=1)

Epoch 1/200
6/6 [==============================] - 2s 374ms/sample - loss: 4395.5757 - acc: 0.0000e+00
Epoch 2/200
6/6 [==============================] - 0s 2ms/sample - loss: 4370.9458 - acc: 0.0000e+00
Epoch 3/200
6/6 [==============================] - 0s 2ms/sample - loss: 4344.3457 - acc: 0.0000e+00
Epoch 4/200
6/6 [==============================] - 0s 2ms/sample - loss: 4315.0698 - acc: 0.0000e+00
Epoch 5/200
6/6 [==============================] - 0s 2ms/sample - loss: 4282.7847 - acc: 0.0000e+00
Epoch 6/200
6/6 [==============================] - 0s 2ms/sample - loss: 4246.7827 - acc: 0.0000e+00
Epoch 7/200
6/6 [==============================] - 0s 2ms/sample - loss: 4206.1680 - acc: 0.0000e+00
Epoch 8/200
6/6 [==============================] - 0s 1ms/sample - loss: 4161.2954 - acc: 0.0000e+00
Epoch 9/200
6/6 [==============================] - 0s 2ms/sample - loss: 4112.3081 - acc: 0.0000e+00
Epoch 10/200
6/6 [==============================] - 0s 2ms/sample - loss: 4056.1875 - acc

In [29]:
y_prediction_stacked_lstm=stacked_LSTM_model.predict(x_input,verbose=1)
y_prediction_stacked_lstm

1/1 [==============================] - 0s 2ms/sample


array([[100.43207]], dtype=float32)

In [30]:
print('Input: \n',x_input)
print('Predicted: ',y_prediction_stacked_lstm)

Input: 
 [[[70]
  [80]
  [90]]]
Predicted:  [[100.43207]]


## Bidirectional LSTM
A Bidirectional LSTM is an LSTM architecture that can improve model performance on sequence prediction problems.

On some sequence prediction problems, it can be beneficial to allow the LSTM model to learn the input sequence both forward and backwards and concatenate both interpretations.

We can implement a Bidirectional LSTM for univariate time series forecasting by wrapping the first hidden layer in a wrapper layer called Bidirectional.

In [31]:
from tensorflow.keras.layers import Bidirectional

In [33]:
bidirectional_LSTM_model=Sequential()
bidirectional_LSTM_model.add(Bidirectional(LSTM(50,activation='relu'),input_shape=(number_of_steps,number_of_features)))
bidirectional_LSTM_model.add(Dense(1))
bidirectional_LSTM_model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bidirectional_1 (Bidirection (None, 100)               20800     
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 101       
Total params: 20,901
Trainable params: 20,901
Non-trainable params: 0
_________________________________________________________________


In [34]:
bidirectional_LSTM_model.compile(optimizer='adam',loss='mse',metrics=['accuracy'])


In [35]:
history=bidirectional_LSTM_model.fit(x_reshaped,y_array,epochs=200,verbose=1)

Epoch 1/200
6/6 [==============================] - 2s 381ms/sample - loss: 5155.8628 - acc: 0.0000e+00
Epoch 2/200
6/6 [==============================] - 0s 1ms/sample - loss: 5036.7378 - acc: 0.0000e+00
Epoch 3/200
6/6 [==============================] - 0s 3ms/sample - loss: 4920.2754 - acc: 0.0000e+00
Epoch 4/200
6/6 [==============================] - 0s 2ms/sample - loss: 4807.4360 - acc: 0.0000e+00
Epoch 5/200
6/6 [==============================] - 0s 2ms/sample - loss: 4697.7920 - acc: 0.0000e+00
Epoch 6/200
6/6 [==============================] - 0s 3ms/sample - loss: 4590.0732 - acc: 0.0000e+00
Epoch 7/200
6/6 [==============================] - 0s 3ms/sample - loss: 4485.4146 - acc: 0.0000e+00
Epoch 8/200
6/6 [==============================] - 0s 3ms/sample - loss: 4381.8320 - acc: 0.0000e+00
Epoch 9/200
6/6 [==============================] - 0s 2ms/sample - loss: 4278.1577 - acc: 0.0000e+00
Epoch 10/200
6/6 [==============================] - 0s 3ms/sample - loss: 4173.8154 - acc

In [36]:
predicted_y_bidirectional_lstm=bidirectional_LSTM_model.predict(x_input,verbose=0)
predicted_y_bidirectional_lstm

array([[101.383286]], dtype=float32)

In [37]:
print('Input: \n',x_input)
print('Predicted: ',predicted_y_bidirectional_lstm)

Input: 
 [[[70]
  [80]
  [90]]]
Predicted:  [[101.383286]]


## Multiple layers of Bidirectional LSTMs

In [42]:
bidirectional_LSTM_model_large=Sequential()
bidirectional_LSTM_model_large.add(Bidirectional(LSTM(50,activation='relu',return_sequences=True),input_shape=(number_of_steps,number_of_features)))
bidirectional_LSTM_model_large.add(Bidirectional(LSTM(50,activation='relu')))
bidirectional_LSTM_model_large.add(Dense(1))
bidirectional_LSTM_model_large.summary()


Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bidirectional_4 (Bidirection (None, 3, 100)            20800     
_________________________________________________________________
bidirectional_5 (Bidirection (None, 100)               60400     
_________________________________________________________________
dense_10 (Dense)             (None, 1)                 101       
Total params: 81,301
Trainable params: 81,301
Non-trainable params: 0
_________________________________________________________________


In [43]:
bidirectional_LSTM_model_large.compile(optimizer='adam',loss='mse',metrics=['accuracy'])


In [44]:
history=bidirectional_LSTM_model_large.fit(x_reshaped,y_array,epochs=200,verbose=1)

Epoch 1/200
6/6 [==============================] - 3s 478ms/sample - loss: 4155.5762 - acc: 0.0000e+00
Epoch 2/200
6/6 [==============================] - 0s 3ms/sample - loss: 4078.2463 - acc: 0.0000e+00
Epoch 3/200
6/6 [==============================] - 0s 4ms/sample - loss: 3993.9229 - acc: 0.0000e+00
Epoch 4/200
6/6 [==============================] - 0s 3ms/sample - loss: 3901.7737 - acc: 0.0000e+00
Epoch 5/200
6/6 [==============================] - 0s 4ms/sample - loss: 3802.2727 - acc: 0.0000e+00
Epoch 6/200
6/6 [==============================] - 0s 3ms/sample - loss: 3697.4729 - acc: 0.0000e+00
Epoch 7/200
6/6 [==============================] - 0s 4ms/sample - loss: 3585.1707 - acc: 0.0000e+00
Epoch 8/200
6/6 [==============================] - 0s 4ms/sample - loss: 3460.8215 - acc: 0.0000e+00
Epoch 9/200
6/6 [==============================] - 0s 3ms/sample - loss: 3320.9785 - acc: 0.0000e+00
Epoch 10/200
6/6 [==============================] - 0s 5ms/sample - loss: 3164.8867 - acc

In [45]:
predicted_y_bidirectional_lstm_large=bidirectional_LSTM_model_large.predict(x_input,verbose=0)
predicted_y_bidirectional_lstm_large

array([[101.854416]], dtype=float32)

In [46]:
print('Input: \n',x_input)
print('Predicted: ',predicted_y_bidirectional_lstm_large)

Input: 
 [[[70]
  [80]
  [90]]]
Predicted:  [[101.854416]]


## Compare Between Bidirectional LSTM and Vanilla LSTM

In [48]:
print('Input: \n',x_input)
print('Predicted -> predicted_y_bidirectional_lstm_large: ',predicted_y_bidirectional_lstm_large)
print('Predicted -> predicted_y_bidirectional_lstm: ',predicted_y_bidirectional_lstm)
print('Predicted -> y_prediction_stacked_lstm: ',y_prediction_stacked_lstm)
print('Predicted -> Vanilla LSTM: ',yhat) # vanilla



Input: 
 [[[70]
  [80]
  [90]]]
Predicted -> predicted_y_bidirectional_lstm_large:  [[101.854416]]
Predicted -> predicted_y_bidirectional_lstm:  [[101.383286]]
Predicted -> y_prediction_stacked_lstm:  [[100.43207]]
Predicted -> Vanilla LSTM:  [[103.32941]]
